export const LOAD_CATALOG_LOADING = "LOAD_CATALOG_LOADING";
export const LOAD_CATALOG_SUCCESS = "LOAD_CATALOG_SUCCESS";
export const LOAD_CATALOG_ERROR = "LOAD_CATALOG_ERROR";
export const SET_PRODUCT_INFO = "SET_PRODUCT_INFO";
export const SET_PRODUCT_CART = "SET_PRODUCT_CART";
export const SET_OPEN_DRAWER = "SET_OPEN_DRAWER";
export const SET_VALUE_FILTER = "SET_VALUE_FILTER";
export const SET_AMOUNT_PRODUCT = "SET_AMOUNT_PRODUCT";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const SET_CEP_VALUE = "SET_CEP_VALUE"; 
export const SET_MODAL_VALUE = "SET_MODAL_VALUE"; 
export const DELETE_CART_VALUE = "DELETE_CART_VALUE";
export const LOAD_CHECKOUT_LOADING = "LOAD_CHECKOUT_LOADING";
export const LOAD_CHECKOUT_SUCCESS = "LOAD_CHECKOUT_SUCCESS";
export const LOAD_CHECKOUT_ERROR = "LOAD_CHECKOUT_ERROR";
export const SET_CLIENT_VALUE = "SET_CLIENT_VALUE";
export const DELETE_CLIENT_VALUE = "DELETE_CLIENT_VALUE"; 

